### ISSUE TITLE
Which broker for what

### ISSUE THREAD

**Issue by z-master42** [reinhard-brandstaedter/solarflow-statuspage#29]
Not really an issue more a question.

But the brokers `mq.zen-iot.com` and `mqtteu.zen-iot.com` are the ones the SolarFlow "talks" to, right? The broker for receiving data (Home Assistant, etc.) is still `mqtt.zen-iot.com` for both?

The difference for the API endpoint is only that one has `v2` and the other `eu` in the URL.

**Comment by reinhard-brandstaedter** [comment]
No, the mqtt.zen-iot.com is the developer broker that you need to register for. It is a bridge from the mq.zen-iot.com broker.
When using the statuspage, it gets the login details ad-hoc and gets it’s data right from the same broker as the hub talks to.
This eliminates the chance of missing data when the dev broker is down.
Since the statuspage also pushes that info to your own broker, i recommend using this data (topic: solarflow-hub/#) for any integration.
Also you can push commands to the statuspage via your mqtt broker, which is then forwarded to the production broker and therefore allows control of the hub (not possible with the dev broker).

Generally for best control of the hub i recommend disconnecting it completely from the cloud brokers.

**Comment by z-master42** [comment]
Ok, thanks for the explanation.

What information does the ...PowerCycle provide?

How do I get my HomeUsage into the status page?

**Comment by reinhard-brandstaedter** [comment]
The HomeUsage chart reads from topic ```solarflow-hub/control/homeUsage```. You will need to make sure to push your smartmeter reader readings there.

The PowerCycle metrics are moving averages provided by Solarflow.

For temperarture. SF only provides maxTemp not current temp, no idea why...

**Comment by z-master42** [comment]
On the status page, what is Battery Power supposed to represent that is not already represented via Charging/Discharging? In my case, the graphic is also empty.
